server:
  port: 8080 # 서버가 사용할 포트 번호 설정
  servlet:
    encoding:
      charset: utf-8 # 서블릿의 응답과 요청 인코딩을 UTF-8로 설정
      force: true # 요청과 응답에 대해 이 인코딩을 강제로 사용하도록 설정
      
spring:
  mvc:
    view: 
      prefix: /WEB-INF/view/ # JSP파일이 위치한 디렉터리 접두사를 설정
      suffix: .jsp # view 이름에 자동을 추가될 파일 확장자를 설정
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:myblogdb;MODE=MySQL
    username: sa
    password:
  sql:
    init:
      schema-locations:
      - classpath:db/table.sql
      data-locations:
      - classpath:db/data.sql
  h2:
    console:
      enabled: true
  output:
    ansi:
      enabled: always # 콘솔 출력에 ANSI 코드를 사용할 수 있도록 설정
mybatis:
  mapper-locations:
    - classpath:mapper/**/*.xml #myBatis 매퍼 파일 위치를 설정
    # **은 모든 디렉터리를 의미, *.xml은 모든 xml 파일을 의미
  configuration:
    map-underscore-to-camel-case: true # 데이터베이스의 언더 스코어 네이밍(column_name)을 카멜 케이스(columnName)로 자동 매핑
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # SQL 로깅 구현체를 설정

logging:
  level:
    org.apache.ibatis: DEBUG      
#  sql:
#    init:
#      data-locations:
#        - classpath:db/data.sql
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    defer-datasource-initialization: true
    
    